
#define SQLITE_ATOMIC_INTRINSICS 1

#define CTIMEOPT_VAL_(opt) #opt
#define CTIMEOPT_VAL(opt) CTIMEOPT_VAL_(opt)

#ifdef SQLITE_ATOMIC_INTRINSICS
"ATOMIC_INTRINSICS=" CTIMEOPT_VAL(SQLITE_ATOMIC_INTRINSICS),
#endif

#define CAT1(x, y) x###y

CAT1(L, CAT1(y, z))
